export const GET_QUESTIONS = "GET_QUESTIONS";
export const REQUEST_QUESTIONS = "REQUEST_QUESTIONS";
export const GET_QUESTION_DETAILS = "GET_QUESTION_DETAILS";
export const REQUEST_QUESTION_DETAILS = "REQUEST_QUESTION_DETAILS";